# Generated by Django 6.0.7 on 2026-07-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'male'), ('Female', 'female')], max_length=50)),
                ('status', models.CharField(choices=[('Available', 'available'), ('Adopted', 'adopted')], default='Available', max_length=50)),
            ],
        ),
    ]
